MIPS: Sibyte: Fix build for SIBYTE_BW_TRACE on BCM1x55 and BCM1x80.
  CC      arch/mips/mm/cerr-sb1.o
arch/mips/mm/cerr-sb1.c: In function sb1_cache_error:
arch/mips/mm/cerr-sb1.c:186:98: error: M_BCM1480_SCD_TRACE_CFG_FREEZE undeclared (first use in this function)
arch/mips/mm/cerr-sb1.c:186:98: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [arch/mips/mm/cerr-sb1.o] Error 1

This happens because 8deab1144b553548fb2f1b51affdd36dcd652aaa [[MIPS]
Updated Sibyte headers] changed the headers but not all the users.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Reported-by: Markos Chandras <markos.chandras@imgtec.com>
Patchwork: https://patchwork.linux-mips.org/patch/5511/
(cherry picked from commit 55e9741a323fb77a11c368de51f8a4fa757311df)